services:
  app:
    build: .
    container_name: authentication-app
    command: fastapi run src/main.py --reload
    ports:
      - "8000:8000"
    volumes:
     - ./src/:/app/src/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

